// Recurrence expansion for calendar items. Pure — no transport, no client.
//
// Semantics (see the module's design decisions):
// - The cadence advances in LOCAL wall-clock terms in the item's timeZone; each
//   instance is converted to a UTC instant individually, so a 9am weekly meeting
//   stays 9am local across a DST transition.
// - Monthly day-31 / yearly Feb-29 slots that don't exist are SKIPPED (RFC 5545),
//   never clamped.
// - COUNT counts occurrences generated by the rule BEFORE exdate removal — an
//   EXDATE'd slot still consumes the count.
// - `until` is an inclusive LOCAL date (YYYY-MM-DD) in the item's timeZone.
// - Occurrence identity is `itemId::originalStartKey`, keyed by the un-overridden
//   cadence slot — stable even when an override moves the display time.

import {
  daysInMonth,
  utcToZonedFields,
  weekdayIndex,
  weekdayOf,
  zonedFieldsToUtc,
} from "./_internal/zoned";
import { addDaysToDateString, parseDateString, startOfDayForDate } from "./datetime";
import type {
  CalendarItem,
  CalendarItemFields,
  ExpandOptions,
  NthWeekday,
  Occurrence,
  OccurrenceOverride,
  RecurrenceRule,
  Weekday,
} from "./types";

/** Hard cap on cadence slots examined per expansion, regardless of `limit`. */
const MAX_ITER = 10_000;
/** Default cap on occurrences returned. */
const DEFAULT_LIMIT = 1000;

type CalDate = { year: number; month: number; day: number };

function pad(n: number): string {
  return String(n).padStart(2, "0");
}

function dateKeyOf(d: CalDate): string {
  return `${d.year}-${pad(d.month)}-${pad(d.day)}`;
}

/** Comparable numeric form of a calendar date (yyyymmdd). */
function dateNum(d: CalDate): number {
  return d.year * 10_000 + d.month * 100 + d.day;
}

/** Pure calendar-day addition; Date.UTC normalizes overflow. */
function addDaysToDate(d: CalDate, days: number): CalDate {
  const t = new Date(Date.UTC(d.year, d.month - 1, d.day + days));
  return { year: t.getUTCFullYear(), month: t.getUTCMonth() + 1, day: t.getUTCDate() };
}

/** Whole days from `a` to `b` (both YYYY-MM-DD; positive when b > a). */
function dateDiffDays(a: string, b: string): number {
  const pa = parseDateString(a);
  const pb = parseDateString(b);
  const ms = Date.UTC(pb.year, pb.month - 1, pb.day) - Date.UTC(pa.year, pa.month - 1, pa.day);
  return Math.round(ms / 86_400_000);
}

/** Merge an override patch over the base item. Patches never change `allDay`. */
function mergeOverride(item: CalendarItem, patch: Partial<CalendarItemFields>): CalendarItem {
  return { ...item, ...patch } as CalendarItem;
}

/** Offset of a weekday within a week starting on MO (MO=0..SU=6). */
function moOffset(w: Weekday): number {
  return (weekdayIndex(w) - weekdayIndex("MO") + 7) % 7;
}

/** Resolve an NthWeekday selector within a month, or undefined if it doesn't exist. */
function resolveNthWeekday(year: number, month: number, sel: NthWeekday): number | undefined {
  const nth = sel.nth;
  if (!Number.isInteger(nth) || nth === 0 || nth < -5 || nth > 5) return undefined;
  const dim = daysInMonth(year, month);
  if (nth > 0) {
    const firstW = weekdayOf(year, month, 1);
    const day = 1 + ((weekdayIndex(sel.weekday) - weekdayIndex(firstW) + 7) % 7) + (nth - 1) * 7;
    return day <= dim ? day : undefined;
  }
  const lastW = weekdayOf(year, month, dim);
  const day = dim - ((weekdayIndex(lastW) - weekdayIndex(sel.weekday) + 7) % 7) - (-nth - 1) * 7;
  return day >= 1 ? day : undefined;
}

/**
 * Lazy ascending sequence of local candidate dates for a rule, starting at the
 * anchor date (candidates strictly before the anchor are skipped).
 */
function* candidateDates(rule: RecurrenceRule, anchor: CalDate): Generator<CalDate> {
  const interval = Math.max(1, rule.interval ?? 1);
  const anchorNum = dateNum(anchor);

  // if/else chain (not switch): every branch loops forever, which Biome's
  // noFallthroughSwitchClause can't see through.
  if (rule.freq === "daily") {
    let d = anchor;
    while (true) {
      yield d;
      d = addDaysToDate(d, interval);
    }
  } else if (rule.freq === "weekly") {
    const days: Weekday[] = rule.byDay?.length
      ? rule.byDay
      : [weekdayOf(anchor.year, anchor.month, anchor.day)];
    const offsets = [...new Set(days.map(moOffset))].sort((a, b) => a - b);
    // Block 0 is the anchor's week, aligned to the implicit weekStart MO.
    const anchorOff = moOffset(weekdayOf(anchor.year, anchor.month, anchor.day));
    let blockStart = addDaysToDate(anchor, -anchorOff);
    while (true) {
      for (const off of offsets) {
        const d = addDaysToDate(blockStart, off);
        if (dateNum(d) < anchorNum) continue; // pre-anchor slots in block 0
        yield d;
      }
      blockStart = addDaysToDate(blockStart, interval * 7);
    }
  } else if (rule.freq === "monthly") {
    let year = anchor.year;
    let month = anchor.month;
    while (true) {
      const dim = daysInMonth(year, month);
      let days: number[];
      if (rule.byWeekday?.length) {
        const resolved = rule.byWeekday
          .map((sel) => resolveNthWeekday(year, month, sel))
          .filter((d): d is number => d !== undefined);
        days = [...new Set(resolved)].sort((a, b) => a - b);
      } else if (rule.byMonthDay?.length) {
        const resolved = rule.byMonthDay
          .map((d) => (d < 0 ? dim + 1 + d : d))
          .filter((d) => d >= 1 && d <= dim);
        days = [...new Set(resolved)].sort((a, b) => a - b);
      } else {
        // Anchor-day cadence: skip the whole month when the day doesn't exist.
        days = anchor.day <= dim ? [anchor.day] : [];
      }
      for (const day of days) {
        const d = { year, month, day };
        if (dateNum(d) < anchorNum) continue;
        yield d;
      }
      month += interval;
      while (month > 12) {
        month -= 12;
        year += 1;
      }
    }
  } else {
    // yearly
    let year = anchor.year;
    while (true) {
      // Skip years where the anchored date doesn't exist (Feb 29 non-leap).
      if (anchor.day <= daysInMonth(year, anchor.month)) {
        yield { year, month: anchor.month, day: anchor.day };
      }
      year += interval;
    }
  }
}

/**
 * Expand `item` into concrete occurrences overlapping `[rangeStart, rangeEnd)`,
 * sorted ascending by effective start. Handles non-recurring items, all four
 * frequencies, EXDATEs, per-instance overrides (moved/deleted), and detached
 * overrides whose cadence slot lies beyond the window.
 */
export function expandOccurrences(
  item: CalendarItem,
  rangeStart: number,
  rangeEnd: number,
  opts?: ExpandOptions,
): Occurrence[] {
  const tz = item.timeZone;
  const limit = opts?.limit ?? DEFAULT_LIMIT;
  const results: Occurrence[] = [];

  // Per-mode anchor + duration.
  let anchor: CalDate;
  let timeOfDay: { hour: number; minute: number; second: number };
  let durationMs = 0;
  let durationDays = 1;
  if (item.allDay) {
    anchor = parseDateString(item.startDate);
    timeOfDay = { hour: 0, minute: 0, second: 0 };
    durationDays = dateDiffDays(item.startDate, item.endDate) + 1;
    if (durationDays < 1) durationDays = 1;
  } else {
    const f = utcToZonedFields(item.start, tz);
    anchor = { year: f.year, month: f.month, day: f.day };
    timeOfDay = { hour: f.hour, minute: f.minute, second: f.second };
    durationMs = item.end - item.start;
  }

  const overrides = new Map<string, OccurrenceOverride>(
    item.overrides?.map((o) => [o.originalStart, o]) ?? [],
  );
  const exdates = new Set(item.exdates ?? []);

  /** Effective [start, end) + all-day dates for one slot, applying any patch. */
  function effectiveInterval(
    originalStart: number,
    slotDateKey: string,
    patch: Partial<CalendarItemFields> | undefined,
  ): { start: number; end: number; startDate?: string; endDate?: string } {
    if (item.allDay) {
      const startDate = patch?.startDate ?? slotDateKey;
      const endDate = patch?.endDate ?? addDaysToDateString(startDate, durationDays - 1);
      return {
        start: startOfDayForDate(startDate, tz),
        end: startOfDayForDate(addDaysToDateString(endDate, 1), tz),
        startDate,
        endDate,
      };
    }
    const start = patch?.start ?? originalStart;
    const end = patch?.end ?? start + durationMs;
    return { start, end };
  }

  function pushOccurrence(
    originalStart: number,
    originalStartKey: string,
    eff: { start: number; end: number; startDate?: string; endDate?: string },
    effItem: CalendarItem,
    isOverride: boolean,
  ): void {
    const occ: Occurrence = {
      itemId: item.id,
      calendarId: item.calendarId,
      kind: effItem.kind,
      allDay: item.allDay,
      title: effItem.title,
      start: eff.start,
      end: eff.end,
      occurrenceKey: `${item.id}::${originalStartKey}`,
      originalStart,
      isOverride,
      item: effItem,
    };
    if (eff.startDate !== undefined) occ.startDate = eff.startDate;
    if (eff.endDate !== undefined) occ.endDate = eff.endDate;
    results.push(occ);
  }

  // ── Non-recurring fast path (exdates/overrides ignored) ────────────────────
  if (!item.recurrence) {
    const originalStart = item.allDay ? startOfDayForDate(item.startDate, tz) : item.start;
    const originalStartKey = item.allDay ? item.startDate : String(originalStart);
    const eff = effectiveInterval(originalStart, item.allDay ? item.startDate : "", undefined);
    if (eff.start < rangeEnd && eff.end > rangeStart) {
      pushOccurrence(originalStart, originalStartKey, eff, item, false);
    }
    return results;
  }

  // ── Recurring path ──────────────────────────────────────────────────────────
  const rule = item.recurrence;
  const visitedKeys = new Set<string>();
  let generatedCount = 0;
  let iter = 0;

  for (const d of candidateDates(rule, anchor)) {
    const localFields = { year: d.year, month: d.month, day: d.day, ...timeOfDay };
    const originalStart = zonedFieldsToUtc(localFields, tz);
    const slotDateKey = dateKeyOf(d);
    const originalStartKey = item.allDay ? slotDateKey : String(originalStart);

    // Termination (per generated slot, pre-EXDATE).
    generatedCount += 1;
    if (rule.count !== undefined && generatedCount > rule.count) break;
    if (rule.until !== undefined && slotDateKey > rule.until) break;
    iter += 1;
    if (iter > MAX_ITER) break;

    // Window bounds: cadence is ascending, so past rangeEnd nothing more emits.
    if (originalStart >= rangeEnd) break;

    const ov = overrides.get(originalStartKey);
    // Cheap pre-window skip on the un-overridden interval (only safe without an
    // override — a patch could move the instance into the window).
    if (!ov) {
      const baseEnd = item.allDay
        ? startOfDayForDate(addDaysToDateString(slotDateKey, durationDays), tz)
        : originalStart + durationMs;
      if (baseEnd <= rangeStart) {
        visitedKeys.add(originalStartKey);
        continue;
      }
    }

    // EXDATE / override handling (both still consume COUNT, handled above).
    if (exdates.has(originalStartKey)) {
      visitedKeys.add(originalStartKey);
      continue;
    }
    if (ov?.deleted) {
      visitedKeys.add(originalStartKey);
      continue;
    }
    const effItem = ov?.patch ? mergeOverride(item, ov.patch) : item;
    const eff = effectiveInterval(originalStart, slotDateKey, ov?.patch);
    if (eff.start < rangeEnd && eff.end > rangeStart) {
      pushOccurrence(originalStart, originalStartKey, eff, effItem, Boolean(ov));
      if (results.length >= limit) break;
    }
    visitedKeys.add(originalStartKey);
  }

  // ── Detached-override pass: overrides whose cadence slot lies beyond the
  //    window but whose patched time falls inside it. ─────────────────────────
  for (const ov of overrides.values()) {
    if (ov.deleted || !ov.patch || visitedKeys.has(ov.originalStart)) continue;
    if (results.length >= limit) break;
    if (exdates.has(ov.originalStart)) continue;
    let originalStart: number;
    let slotDateKey: string;
    if (item.allDay) {
      slotDateKey = ov.originalStart;
      try {
        originalStart = startOfDayForDate(slotDateKey, tz);
      } catch {
        continue; // malformed key — ignore
      }
    } else {
      originalStart = Number(ov.originalStart);
      if (!Number.isFinite(originalStart)) continue;
      slotDateKey = "";
    }
    const eff = effectiveInterval(originalStart, slotDateKey, ov.patch);
    if (eff.start < rangeEnd && eff.end > rangeStart) {
      pushOccurrence(originalStart, ov.originalStart, eff, mergeOverride(item, ov.patch), true);
    }
  }

  results.sort((a, b) => a.start - b.start);
  return results;
}
