// Type definitions for the pure-logic calendar module (`sdk.calendar`).
// No runtime code — see datetime.ts / recurrence.ts / sync-adapter.ts.

// ─── Item taxonomy ────────────────────────────────────────────────────────────
export type CalendarItemKind = "event" | "task" | "milestone" | "log";

export type ItemLink = {
  /** "conversation" → unified conversation id; "url" → external href; "entity" → app-defined. */
  type: "conversation" | "url" | "entity";
  value: string;
  label?: string;
};

// ─── Recurrence ───────────────────────────────────────────────────────────────
export type Frequency = "daily" | "weekly" | "monthly" | "yearly";
export type Weekday = "SU" | "MO" | "TU" | "WE" | "TH" | "FR" | "SA";

/** nth-weekday selector for monthly rules, e.g. { nth: 3, weekday: "MO" } = 3rd Monday;
 *  nth in -5..-1 counts from month end (-1 = last). nth must be in [-5,-1] ∪ [1,5], nonzero. */
export type NthWeekday = { nth: number; weekday: Weekday };

export interface RecurrenceRule {
  freq: Frequency;
  /** ≥ 1; default 1. Values < 1 are coerced to 1 on expansion. */
  interval?: number;
  /** weekly: the weekdays in each recurring week. Ignored for other freqs. */
  byDay?: Weekday[];
  /** monthly: days of month, 1..31 or -31..-1 (-1 = last day). Non-existent days are SKIPPED. */
  byMonthDay?: number[];
  /** monthly: nth-weekday selectors. If both set, byWeekday wins over byMonthDay. */
  byWeekday?: NthWeekday[];
  /** Inclusive local end date (YYYY-MM-DD) in the item's timeZone. Mutually exclusive with count. */
  until?: string;
  /** Total occurrences generated by the rule, incl. the first, counted BEFORE exdate removal. */
  count?: number;
}

/** A cancelled or modified single occurrence, keyed by the cadence's original start. */
export interface OccurrenceOverride {
  /** originalStartKey: epoch-ms string (timed) or YYYY-MM-DD (all-day) of the un-overridden slot. */
  originalStart: string;
  /** true → this occurrence is removed (a targeted EXDATE-equivalent with identity). */
  deleted?: boolean;
  /** Patch applied over the base item for this instance. */
  patch?: Partial<CalendarItemFields>;
}

// ─── Item ─────────────────────────────────────────────────────────────────────
/** Fields common to both timed and all-day items (the overridable surface). */
export interface CalendarItemFields {
  title: string;
  description?: string;
  location?: string;
  color?: string; // app-defined token or hex
  tags?: string[];
  links?: ItemLink[];
  /** task state (kind === "task"). */
  done?: boolean;
  completedAt?: number; // epoch ms
  // timing overrides (an override may move an instance):
  start?: number; // timed only
  end?: number; // timed only
  startDate?: string; // all-day only
  endDate?: string; // all-day only
}

interface CalendarItemBase extends CalendarItemFields {
  id: string;
  calendarId: string;
  kind: CalendarItemKind;
  /** IANA tz. For all-day items this is the anchor zone used for grid placement & recurrence. */
  timeZone: string;
  recurrence?: RecurrenceRule;
  /** Bare EXDATEs: originalStartKeys to cancel (in addition to overrides with deleted:true). */
  exdates?: string[];
  overrides?: OccurrenceOverride[];
  createdAt: number; // epoch ms
  updatedAt: number; // epoch ms
}

export interface TimedItem extends CalendarItemBase {
  allDay: false;
  start: number; // epoch ms UTC (inclusive)
  end: number; // epoch ms UTC (exclusive); milestone: end === start
}

export interface AllDayItem extends CalendarItemBase {
  allDay: true;
  startDate: string; // YYYY-MM-DD (inclusive)
  endDate: string; // YYYY-MM-DD (inclusive)
}

export type CalendarItem = TimedItem | AllDayItem;

// ─── Calendar container ───────────────────────────────────────────────────────
export interface CalendarMeta {
  id: string;
  name: string;
  color?: string;
  /** Default tz for new items authored in this calendar. */
  timeZone?: string;
  /** UI hide/show; expansion ignores this. */
  hidden?: boolean;
  createdAt: number;
  updatedAt: number;
}

// ─── Expansion outputs ────────────────────────────────────────────────────────
export interface Occurrence {
  itemId: string;
  calendarId: string;
  kind: CalendarItemKind;
  allDay: boolean;
  title: string;
  /** Effective interval as UTC instants. All-day: start = start-of-day, end = exclusive next-day boundary, both in item.timeZone. */
  start: number;
  end: number; // exclusive
  /** Present for all-day occurrences. */
  startDate?: string;
  endDate?: string; // inclusive
  /** itemId::originalStartKey — stable identity. */
  occurrenceKey: string;
  originalStart: number; // UTC instant of the un-overridden cadence slot
  isOverride: boolean;
  /** The effective item view for this instance (base merged with any override patch). */
  item: CalendarItem;
}

export interface ExpandOptions {
  /** Max occurrences returned; default 1000. Internal MAX_ITER candidate cap regardless. */
  limit?: number;
}

// ─── Date-math value types ────────────────────────────────────────────────────
export interface ZonedFields {
  year: number; // full year
  month: number; // 1..12
  day: number; // 1..31
  hour: number; // 0..23
  minute: number; // 0..59
  second: number; // 0..59
  ms?: number; // 0..999
}

export interface DayCell {
  date: string; // YYYY-MM-DD
  start: number; // start-of-day UTC instant in tz
  end: number; // exclusive next-day boundary
  dayOfMonth: number;
  weekday: Weekday;
  /** false for leading/trailing days from adjacent months. */
  inCurrentMonth: boolean;
}

export interface Range {
  start: number;
  end: number;
} // [start, end)
