#!/usr/bin/env bun
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const LOGOS_DIR = join(import.meta.dir, "..", "src", "assets", "logos");
const OUT_FILE = join(import.meta.dir, "..", "src", "resources", "logos.generated.ts");

const slugs = readdirSync(LOGOS_DIR)
  .filter((f) => f.endsWith(".svg"))
  .map((f) => basename(f, ".svg"))
  .sort();

// URL-encoded SVG is ~30% smaller than base64 and compresses better under gzip.
const toDataUri = (svg: string) =>
  `data:image/svg+xml;utf8,${encodeURIComponent(svg.trim())}`;

const entries = slugs.map((slug) => ({
  slug,
  dataUri: toDataUri(readFileSync(join(LOGOS_DIR, `${slug}.svg`), "utf8")),
}));

const union = slugs.map((s) => JSON.stringify(s)).join(" | ");
const mapBody = entries
  .map((e) => `  ${JSON.stringify(e.slug)}: ${JSON.stringify(e.dataUri)},`)
  .join("\n");

const source = `// AUTO-GENERATED by scripts/generate-logos.ts — do not edit.

export type LogoSlug = ${union};

export const LOGO_DATA_URIS: Record<LogoSlug, string> = {
${mapBody}
};
`;

writeFileSync(OUT_FILE, source);
console.log(`Generated ${entries.length} logo entries → ${OUT_FILE}`);
